# docker-compose.yml - FOR LOCAL DEVELOPMENT ONLY
version: '3.8'

services:
<<<<<<< HEAD
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/api

=======
>>>>>>> 03b28fa (feat: separate CI/CD workflows and update domain to jagasewa.cloud)
  backend:
    build: ./backend
    ports:
<<<<<<< HEAD
      - "8000:8000"
=======
      - "80:80"
    environment:
      - DB_HOST=${RDS_ENDPOINT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - API_URL=https://api.jagasewa.cloud
>>>>>>> 03b28fa (feat: separate CI/CD workflows and update domain to jagasewa.cloud)
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_HOST=localhost
      - DB_NAME=jagasewa_db
      - DB_USER=root
      - DB_PASSWORD=