# docker-compose.yml - FOR LOCAL DEVELOPMENT ONLY
version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/api

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_HOST=localhost
      - DB_NAME=jagasewa_db
      - DB_USER=root
      - DB_PASSWORD=