version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: jagasewa_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: jagasewa_backend
    restart: always
    ports:
      - "9000:80"
    volumes:
      - ./backend:/var/www/html
