version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: jagasewa_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: jagasewa_backend
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
    extra_hosts:
      - "host.docker.internal:172.17.0.1"  # Allow backend to access EC2 MariaDB