version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: php_backend
    ports:
      - "9000:80"
    volumes:
      - ./backend:/var/www/html
