name: Infrastructure Deploy (Terraform)

on:
  push:
    branches: [main]
    paths: ['infra/**']
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - prod

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Terraform Init
      working-directory: ./infra
      run: terraform init

    - name: Terraform Plan
      working-directory: ./infra
      env:
        TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      run: |
        terraform plan -var-file="env/${{ github.event.inputs.environment || 'dev' }}.tfvars"

    - name: Terraform Apply
      working-directory: ./infra
      env:
        TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      run: |
        terraform apply -auto-approve -var-file="env/${{ github.event.inputs.environment || 'dev' }}.tfvars"